---
name: Bluefin Wallpapers Extra
on:
  workflow_dispatch:

jobs:
  create-release:
    name: Create Release for Bluefin Wallpapers with Gnome and KDE support
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # We need a newish version of kimageformats, 24.04 doesn't have it
    container: docker.io/library/ubuntu:25.04

    steps:

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Create tarball
        shell: bash
        run: |
          mkdir -p output/packaging/kde/
          mkdir -p output/packaging/gnome/images
          for wp in "collapse" "prey" "tenacious-pterosaur"; do
            mv wallpapers/$wp/kde/*.avif output/packaging/kde/
            cp wallpapers/$wp/gnome/* output/packaging/gnome/images
            cp -R wallpapers/$wp/gnome/gnome-background-properties output/packaging/gnome/
          done
          cd output/packaging && tar -acvf bluefin-wallpapers-extra.tar.zstd *

      - name: Determine tag
        id: tag
        run: echo "tag=v$(date --iso-8601=date)" >> "$GITHUB_OUTPUT"

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          tag:   ${{ steps.tag.outputs.tag }}
          allowUpdates: true
          name:  "${{ steps.tag.outputs.tag }}"
          artifacts: "output/packaging/bluefin-wallpapers-extra.tar.zstd"
          token: ${{ secrets.GITHUB_TOKEN }}
